/* Generated by Vite with a content version and the exact build assets. */
const CACHE = 'ecolink-8e553dbf1ea5';
const ASSETS = ["index.html","manifest.webmanifest","icons/icon.svg","icons/icon-192.png","icons/icon-512.png","assets/tokens/grass/token-grass-idle-128-v1.webp","assets/tokens/grasshopper/token-grasshopper-idle-128-v1.webp","assets/tokens/frog/token-frog-idle-128-v1.webp","assets/tokens/snake/token-snake-idle-128-v1.webp","assets/tokens/disturbance/token-disturbance-idle-128-v1.webp","assets/tokens/grass/token-grass-blink-layer-128-v1.webp","assets/tokens/grasshopper/token-grasshopper-blink-layer-128-v1.webp","assets/tokens/frog/token-frog-blink-layer-128-v1.webp","assets/tokens/snake/token-snake-blink-layer-128-v1.webp","assets/stages/school-garden/stage-school-garden-bg-1920x1080-v1.webp","assets/stages/rice-field/stage-rice-field-bg-1920x1080-v1.webp","assets/tokens/phytoplankton/token-phytoplankton-idle-128-v2.webp","assets/tokens/phytoplankton/token-phytoplankton-blink-layer-128-v2.webp","assets/tokens/zooplankton/token-zooplankton-idle-128-v2.webp","assets/tokens/zooplankton/token-zooplankton-blink-layer-128-v2.webp","assets/tokens/small-fish/token-small-fish-idle-128-v2.webp","assets/tokens/small-fish/token-small-fish-blink-layer-128-v2.webp","assets/tokens/big-fish/token-big-fish-idle-128-v2.webp","assets/tokens/big-fish/token-big-fish-blink-layer-128-v2.webp"];
const scope = self.registration.scope;
const appUrl = (path) => new URL(path, scope).href;

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS.map(appUrl))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      caches
        .keys()
        .then((keys) =>
          Promise.all(
            keys
              .filter((key) => key.startsWith('ecolink-') && key !== CACHE)
              .map((key) => caches.delete(key)),
          ),
        ),
      self.clients.claim(),
    ]),
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
  if (event.data?.type === 'CHECK_READY') {
    event.waitUntil(
      caches
        .open(CACHE)
        .then((cache) => Promise.all(ASSETS.map((path) => cache.match(appUrl(path)))))
        .then((responses) => event.ports?.[0]?.postMessage({ ready: responses.every(Boolean) }))
        .catch(() => event.ports?.[0]?.postMessage({ ready: false })),
    );
  }
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin || !url.href.startsWith(scope)) return;
  if (event.request.mode === 'navigate') {
    event.respondWith(
      caches.match(appUrl('index.html')).then((cached) => cached || fetch(event.request)),
    );
    return;
  }
  event.respondWith(caches.match(event.request).then((cached) => cached || fetch(event.request)));
});
